Первый вариант 14 спринт
Bomsi24/java-shareit pull request #1
Opened 2024-07-20 01:36 UTC by Bomsi24

2024-07-20 13:49 UTC, afomkina requested changes

2024-07-20 13:49 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemUsersDto> getAllItems(@RequestHeader("X-Sharer-User-Id") int userId) {
Нужно вынести повторяющийся хэдер в отдельный класс и сделать его публичной константой, чтобы избежать дублирований в других классах. Чтобы быстро поправить все значения, можно воспользоваться горячими клавишами в IDEA: [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2024-07-20 13:49 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        for (List<Item> itemList : items.values()) {
Нужно воспользоваться [stream api](https://struchkov.dev/blog/ru/java-stream-api/)

2024-07-20 13:49 UTC, afomkina commented on src/main/java/ru/practicum/shareit/item/ItemRepositoryImpl.java
> +        items.values().forEach(allItems::addAll);
Лучше использовать [stream.flatMap()](https://struchkov.dev/blog/ru/java-stream-api/#:~:text=CONCURRENT%3A%20%D1%81%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D1%8F%D1%8E%D1%82%D1%81%D1%8F.-,flatMap(),-%D0%9C%D0%B5%D1%82%D0%BE%D0%B4%20flatMap())

2024-07-20 13:49 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    private boolean checkEmail(String email) {
_Дополнительные оптимизации_
Чтобы проверка почты проходила за [O(1)](https://skillbox.ru/media/code/big-o-notation-chto-eto-takoe-i-kak-eye-poschitat/), нужно завести Set, куда при добавлении нового пользователя мы будем класть его email. Соответственно, перед тем как добавить пользователя, нужно будет посмотреть, есть ли уже в сете подобный email, если есть - то пользователь с таким email уже существует.

Так как поиск и вставка в сете работают в среднем за O(1), то наш алгоритм поиска одинаковых email тоже будет работать в среднем за O(1), а это гораздо быстрее, чем пройтись по всем элементам списка O(n)

2024-07-20 14:39 UTC, Bomsi24 commented
Привет. Исправил замечания

2024-07-21 22:03 UTC, afomkina approved these changes

2024-07-21 23:47 UTC, merged