15 спринт
Bomsi24/java-shareit pull request #2
Opened 2024-08-04 14:48 UTC by Bomsi24

2024-08-06 13:50 UTC, afomkina requested changes
У тебя получилась отличная работа, она полностью соответствует тз и выглядит максимально чисто. Оставила пару комментариев для дополнительного изучения

2024-08-06 13:50 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/mapper/BookingMapper.java
>                  .id(booking.getId())
Метод нигде не используется

2024-08-06 13:50 UTC, afomkina commented on src/main/resources/schema.sql
_Опционально_
Предлагаю попробовать добавить [индексы](https://tproger.ru/articles/indeksy-v-postgresql/), чтобы ускорить поиск

2024-08-06 13:50 UTC, afomkina commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    private List<Booking> retrieveBookingsByItems(List<Item> items, BookingState bookingState, Sort sort) {
_Задание со "*"_
Данный блок кода можно оптимизировать с помощью паттерна проектирования 
[Цепочка обязанностей](https://refactoring.guru/ru/design-patterns/chain-of-responsibility) (сайт может не открываться без vpn).
Предлагаю изучить этот паттерн и попробовать реализовать его.

В коммерческой разработке очень часто используются паттерны проектирования, так как код становится более чистым и структурированным. А еще его становится проще поддерживать и масштабировать. 

А еще их часто спрашивают на собеседованиях 😉

2024-08-06 21:48 UTC, Bomsi24 commented
Привет. Исправил замечание)

2024-08-07 14:49 UTC, afomkina approved these changes
Клево, что разобрался с дополнительными заданиями, молодец 🔥

2024-08-07 14:50 UTC, merged